# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingcom_block_id', models.CharField(max_length=100)),
                ('positive_votes', models.IntegerField()),
                ('negative_votes', models.IntegerField()),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assemblage.Group'),
        ),
        migrations.AddField(
            model_name='block',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
