# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Assemblage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=100)),
                ('hotel_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('positive_votes', models.IntegerField()),
                ('negative_votes', models.IntegerField()),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelingroup_requests_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assemblage.Group')),
                ('voters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='creating_user',
        ),
        migrations.RemoveField(
            model_name='block',
            name='group',
        ),
        migrations.RemoveField(
            model_name='block',
            name='voters',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
