# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assemblage', '0003_auto_20161014_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='destination',
            new_name='dest_name',
        ),
        migrations.AddField(
            model_name='group',
            name='dest_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelingroup',
            name='hotel_name',
            field=models.CharField(default='hotel_name_1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelingroup',
            name='hotel_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelingroup',
            name='hotel_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelingroup',
            name='total_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
