# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Assemblage', '0005_group_dest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_done',
            field=models.ManyToManyField(related_name='group_users_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='group_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
